services:
  db:
    image: postgres:16-alpine
    container_name: gestor-votos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gestor
      POSTGRES_PASSWORD: gestor
      POSTGRES_DB: gestor_votos
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
